name: RSpec CI

on:
  # allow running action manually
  workflow_dispatch:
  # trigger on push to master branch
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
      - run: bundle install
      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate
      - run: bundle exec rspec
